doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"
    types:
      mail_id: EmailSender\Infrastructure\Persistence\Doctrine\Types\MailIdType
      subject: EmailSender\Infrastructure\Persistence\Doctrine\Types\SubjectType

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    controller_resolver:
      auto_mapping: true
    mappings:
      EmailSender:
        is_bundle: false
        type: xml
        dir: "%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping"
        prefix: 'EmailSender\Domain\Model'  