services:
  nginx-devlocal:
    container_name: "emailsender-nginx"
    image: "emailsender-nginx:latest"
    build:
      context: ../.
      dockerfile: docker/nginx/Dockerfile
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - php-devlocal
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - "$PWD/..:/var/emailsender"
    ports:
      - "172.17.0.1:11680:80"
    networks:
      - emailsender-networks

  php-devlocal:
    container_name: emailsender-php
    image: "emailsender-php:latest"
    build:
      context: ../.
      dockerfile: emailsender/docker/php/Dockerfile
      tags:
        - php-emailsender
    user: 1000:1000
    volumes:
      - "$PWD/..:/var/emailsender"
      - "$PWD/..:$PWD/.."    
    working_dir: $PWD/..
    env_file:
      - secret.env
    networks:
      - emailsender-networks

  emailsender-swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: "emailsender-swagger-ui"
    restart: always
    environment:
      PORT: 8080
      SUPPORTED_SUBMIT_METHODS: "['get', 'post', 'put', 'delete', 'patch']"
      SWAGGER_JSON: /v1/doc.yaml
    volumes:
      - ./docker/swagger/v1:/v1
    ports:
      - "172.17.0.1:11602:8080"
    networks:
      - emailsender-networks

  emailsender-mariadb:
    image: emailsender-mariadb:latest
    container_name: "emailsender-mariadb"
    build:
      dockerfile: docker/mariadb/Dockerfile
    restart: always
    volumes:
      - /home/debian/project/emailsender-mariadb/_data:/var/lib/mysql
      - ../../mariabackup:/backup
    env_file:
      - ./docker/mariadb/db.env
    networks:
      - emailsender-networks

  emailsender-phpmyadmin:
    image: phpmyadmin:latest
    container_name: "emailsender-phpmyadmin"
    restart: always
    environment:
      - PMA_HOST=emailsender-mariadb
    depends_on:
      - emailsender-mariadb
    ports:
      - "172.17.0.1:11690:80"
    networks:
      - emailsender-networks

  
networks:
  emailsender-networks:
    driver: bridge
    enable_ipv6: true
    name: emailsender-networks
    ipam:
      config:
        - subnet: fdff:1:2e::/112
          gateway: fdff:1:2e::1

volumes:
  emailsender-db:
