services:
  nginx-devlocal:
    container_name: "emailsender-nginx"
    image: "emailsender-nginx:latest"
    build:
      context: ../.
      dockerfile: docker/nginx/Dockerfile
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - php-devlocal
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - "$PWD/..:/var/emailsender"
    ports:
      - "33080:80"
      - "2443:443"
    networks:
      - emailsender-networks

  php-devlocal:
    container_name: emailsender-php
    image: "emailsender-php:latest"
    build:
      context: ../.
      dockerfile: docker/php/Dockerfile
      tags:
        - php-emailsender
    user: 1000:1000
    volumes:
      - "$PWD/..:/var/emailsender"
      - "$PWD/..:$PWD/.."    
    working_dir: $PWD/..
    networks:
      - emailsender-networks

networks:
  emailsender-networks:
    driver: bridge
    enable_ipv6: true
    name: emailsender-networks
    ipam:
      config:
        - subnet: fdff:1:1::/112
          gateway: fdff:1:1::1

volumes:
  emailsender-db:
