# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  email.repository:
    public: true
    autowire: true
    class: EmailSender\Infrastructure\Persistence\Mail\EmailSenderRepositoryDoctrine

  email.providerFactory:
    public: true
    autowire: true
    class: EmailSender\Infrastructure\Provider\FactoryEmailProvider

  EmailSender\Infrastructure\Api\V1\SendMailController:
    autowire: true
    arguments:
      $repository: '@email.repository'
      $emailProviderFactory: '@email.providerFactory'



  EmailSender\Domain\Model\Mail\EmailSenderRepositoryInterface: "@email.repository"
  EmailSender\Application\Service\SendMail\AbstractFactoryEmailProvider: "@email.providerFactory"
  EmailSender\Infrastructure\Api\V1\:
    resource: "../src/Infrastructure/Api/V1/"
    tags: ["controller.service_arguments"]


